services:
  celery_worker:
    dns:
      - 8.8.8.8
      - 1.1.1.1
    build:
      context: ../backend
      dockerfile: ../celery/Dockerfile
      network: host
    command: celery -A backend.Defolio worker --loglevel=info
    volumes:
      - ../backend:/app/backend
    env_file:
      - ../.env
    networks:
      - default
    environment:
      - PYTHONPATH=/app

networks:
  default:
    external: true
    name: shared_network
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

