services:
  ng-manager:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./static:/static
    networks:
      - default

networks:
  default:
    external: true
    name: shared_network
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450