services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - default

networks:
  default:
    external: true
    name: shared_network
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450